services:
  api:
    container_name: gallery-api
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "
      npx prisma migrate deploy &&
      node dist/main.js
      "

  db:
    image: mysql:8.0
    container_name: gallery-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gallery_db
      MYSQL_USER: gallery_user
      MYSQL_PASSWORD: StrongPassword123!
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
